name: software

description: An Ubuntu software app made with Flutter.

publish_to: "none"

version: 0.0.2-alpha

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  badges: ^2.0.3
  collection: ^1.16.0
  connectivity_plus: ^2.3.1
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.0
  handy_window: ^0.1.4
  image: ^3.1.3
  intl: ^0.17.0
  liquid_progress_indicator: ^0.4.0
  package_info_plus: ^1.4.2
  packagekit: ^0.2.1
  palette_generator: ^0.3.3
  provider: ^6.0.2
  quiver: ^3.1.0
  safe_change_notifier: ^0.1.0+1
  snapd:
    git: https://github.com/canonical/snapd.dart
  ubuntu_service: ^0.1.0
  url_launcher: ^6.1.2
  version: ^2.0.0
  xdg_icons:
    git:
      url: https://github.com/ubuntu-flutter-community/xdg_icons
      path: packages/xdg_icons
  yaru: ^0.3.2
  yaru_colors: ^0.1.0
  yaru_icons:
    git: https://github.com/ubuntu/yaru_icons.dart
  yaru_widgets:
    git: https://github.com/ubuntu/yaru_widgets.dart

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
