name: app_store
description: App Store
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  args: ^2.4.2
  cached_network_image: ^3.2.3
  collection: ^1.17.0
  file: ^6.1.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.15+1
  flutter_riverpod: ^2.3.6
  github: ^9.15.1
  gtk: ^2.1.0
  handy_window: ^0.3.1
  meta: ^1.9.1
  path: ^1.8.3
  shimmer: ^3.0.0
  snapcraft_launcher: ^0.1.0
  snapd: ^0.4.10
  ubuntu_localizations: ^0.3.3
  ubuntu_service: ^0.2.2
  ubuntu_test: ^0.1.0-0
  ubuntu_widgets: ^0.1.2
  xdg_directories: ^1.0.0
  yaru: ^0.9.0
  yaru_icons: ^1.0.4
  yaru_widgets: ^2.5.0

dev_dependencies:
  build_runner: ^2.4.5
  fake_async: ^1.3.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  melos: ^3.0.0
  mockito: 5.4.2

dependency_overrides:
  snapd:
    git:
      url: https://github.com/canonical/snapd.dart
      ref: json
  yaru_widgets:
    git:
      url: https://github.com/ubuntu/yaru_widgets.dart
      ref: 412dd638fa44c8cde9986646fa0130e79285761c

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/snap-store.desktop
