name: app_center_ratings_client
description: Dart client for the App Center Rating service
repository: https://github.com/ubuntu/app-center/tree/main/packages/app_center_ratings_client
version: 1.0.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  fixnum: ^1.1.0
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  grpc: ^4.0.1
  meta: ^1.15.0
  protobuf: ^3.1.0
  protoc_plugin: ^21.1.2

dev_dependencies:
  build_runner: ^2.4.12
  mockito: ^5.4.4
  test: ^1.25.8
  ubuntu_lints: ^0.4.0
