name: app_center_ratings_client
description: Dart client for the App Center Rating service
repository: https://github.com/ubuntu/app-center/tree/main/packages/app_center_ratings_client
version: 1.0.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  fixnum: ^1.1.0
  freezed: ^2.4.1
  freezed_annotation: ^2.4.1
  grpc: ^3.1.0
  meta: ^1.7.0
  protobuf: ^3.0.0
  protoc_plugin: ^21.0.1

dev_dependencies:
  build_runner: ^2.4.6
  mockito: ^5.4.3
  test: ^1.21.0
  ubuntu_lints: ^0.3.1
