name: app_center
description: App Center
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: 3.13.9

dependencies:
  app_center_ratings_client: ^1.0.0
  appstream: ^0.2.8
  args: ^2.4.2
  cached_network_image: ^3.3.0
  clock: ^1.1.1
  collection: ^1.17.2
  crypto: ^3.0.3
  dbus: ^0.7.10
  file: ^6.1.4
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  flutter_html: ^3.0.0-beta.2
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.18
  flutter_riverpod: ^2.4.6
  github: ^9.20.0
  glib: ^0.0.1
  gtk: ^2.1.0
  handy_window: ^0.3.1
  intl: ^0.18.1
  jwt_decode: ^0.3.1
  meta: ^1.9.1
  package_info_plus: ^4.2.0
  packagekit: ^0.2.6
  path: ^1.8.3
  shimmer: ^3.0.0
  snapcraft_launcher: ^0.1.0
  snapd: ^0.4.11
  snowball_stemmer: ^0.1.0
  ubuntu_localizations: ^0.3.4
  ubuntu_logger: ^0.1.0
  ubuntu_service: ^0.3.0
  ubuntu_test: ^0.1.0-0
  ubuntu_widgets: ^0.3.1
  url_launcher: ^6.2.1
  xdg_directories: ^1.0.3
  yaru: ^1.2.0
  yaru_icons: ^2.2.2
  yaru_test: ^0.1.5
  yaru_widgets: ^3.3.0

dev_dependencies:
  build_runner: ^2.4.6
  fake_async: ^1.3.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: 5.4.3
  ubuntu_lints: ^0.3.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
