name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  with-flutter-action:
    name: with-flutter-action
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.3.x"
      - run: sudo apt update
      - run: sudo apt -y install git curl cmake ninja-build make clang libgtk-3-dev pkg-config
      - run: flutter build linux -v

  with-flutter-snap:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: sudo snap install flutter --classic
      - run: flutter doctor -v
      - run: git -C $HOME/snap/flutter/common/flutter checkout 3.3.10
      - run: flutter build linux -v
