name: cla-check
on: [pull_request_target]

jobs:
  cla-check:
    if: github.event.pusher.name != 'weblate'
    runs-on: ubuntu-20.04
    steps:
      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}'
      - name: Check if CLA signed
        uses: canonical/has-signed-canonical-cla@v1
